### ISSUE TITLE
[Feature Request] WWN is required in LocalDisk Attributes

### ISSUE THREAD

**Issue by SSmallMonster** [hwameistor/hwameistor#1222]
**WWN** is an identifier for localdisk, for now we have `SerialNumber` already but in some environments, `SerialNumber` is not enough to distinguish disk. 

So, we should consider **WWN** as one of elements which use to identify a speial disk.

FYI: #1220

**Comment by SSmallMonster** [comment]
@hikariwo wiil work on this

**Comment by sun7927** [comment]
Actually, WWN is not for the real local disk, but for the "local disk" attached from a SAN storage system. In this situation, we should think about more than just adding a WWN

**Comment by sun7927** [comment]
I suggest to discuss more about it before moving forward

**Comment by hikariwo** [comment]
I take

> I suggest to discuss more about it before moving forward

Other information like devLink may change with higher frequency than **WWN**. In this situation, we discuss the consistency on the localdisk name generation and the disk discovery to make the system more reasonable.

**Comment by sun7927** [comment]
> > I suggest to discuss more about it before moving forward
> 
> Other information like devLink may change with higher frequency than **WWN**. In this situation, we discuss the consistency on the localdisk name generation and the disk discovery to make the system more reasonable.

devLink's change has already been considered in the local disk management, @SSmallMonster can you confirm?

**Comment by sun7927** [comment]
Think about the best way to manage the local disk, besides just discover the disk attributes, it should find out where the local disk comes from. For example, some disks are real local disk (SSD, HDD), some are from SAN, Ceph/RBD, or NAS(??).

**Comment by AmazingPangWei** [comment]
Yes, I agree with @sun7927. In the short term, adding WWN as a LocalDisk attribute is a fast way to fix issue #1220. But in the long term, hwameistor should identify different disk types (such as SAN/RBD/NAS, etc.) and generate unique identifier for them. 

So may we can design a interface which simply generates a identifier. Different disk types should implement this interface. For now, we can implement this interface for normal local disks and **SAN disks**(taking WWN into account). Other disk types can easily expand when necessary in the future.

**Comment by SSmallMonster** [comment]
> > > I suggest to discuss more about it before moving forward
> > 
> > 
> > Other information like devLink may change with higher frequency than **WWN**. In this situation, we discuss the consistency on the localdisk name generation and the disk discovery to make the system more reasonable.
> 
> devLink's change has already been considered in the local disk management, @SSmallMonster can you confirm?

yes, devLink is one of the element that generate UUID

**Comment by SSmallMonster** [comment]
@hikariwo will work on this to distinguish different disks that attached from different storage system.

**Comment by hikariwo** [comment]
The feature of identifying Ceph component is exploring.There are many differences between the  `cephadmin` version(since Octopus version ) and `ceph deploy` verison(end at Nautilus verison).And the Nautilus verison looks like ending the lifecycle and have not any supports since 06/30/2021.Does we move forward and adapt the version after Octopus version? And 
looks like delivering the `ceph.conf, admin.keyring` from leader node to followers node is a popular operation that we use `ceph-deploy admin master node1 node2 ` command at `ceph-deploy` verison, so that the follower node can get the cluster info. But looks like at `cephadm` version, without similar command are supported. But we could still copy the `ceph.conf, admin.keyring` and then deliver them to other nodes. Does look up the cluster info on follower node is a reasonable operation since Octopus version?
